import os
from langchain.tools import StructuredTool

def read_execution_report_file(case_path: str, return_not_found_message: bool = False) -> str:
    """
    Reads the execution report saved by ExecutionAgent from the case directory.

    Args:
        case_path: Absolute path to the OpenFOAM case directory.
        return_not_found_message: If True, return a human-readable message when the report is missing;
            otherwise return an empty string on missing report.

    Returns:
        Report content, an empty string if missing (default), or an error message when file read fails.
    """
    if not case_path:
        return "No case_path provided for reading execution_report.md." if return_not_found_message else ""

    report_path = os.path.join(case_path, "execution_report.md")
    if os.path.exists(report_path):
        try:
            with open(report_path, "r") as f:
                return f.read()
        except Exception as e:
            return f"Error reading execution report: {e}"

    if return_not_found_message:
        return "No execution report found. The ExecutionAgent has not run yet or did not save the report."
    return ""

def get_execution_report_tool() -> StructuredTool:
    """
    Tool for other agents (like Orchestrator) to read the generated execution report.
    """
    return StructuredTool.from_function(
        func=lambda case_path: read_execution_report_file(case_path, return_not_found_message=True),
        name="get_execution_report",
        description="Get the existing execution report generated by the Execution Agent. Requires the absolute case_path."
    )
