import os
from langchain.tools import StructuredTool

def _truncate_report(text: str, max_chars: int) -> str:
    max_chars = max(1000, min(int(max_chars), 20000))
    if len(text) <= max_chars:
        return text
    return text[:max_chars] + f"\n[truncated after {max_chars} characters]"


def read_physics_report_file(case_path: str, return_not_found_message: bool = False, max_chars: int = 6000) -> str:
    """
    Reads the physics analysis report saved by PhysicsAnalystAgent from the case directory.

    Args:
        case_path: Absolute path to the OpenFOAM case directory.
        return_not_found_message: If True, return a human-readable message when the report is missing;
            otherwise return an empty string on missing report.

    Returns:
        Report content, an empty string if missing (default), or an error message when file read fails.
    """
    if not case_path:
        return "No case_path provided for reading physics_report.md." if return_not_found_message else ""

    report_path = os.path.join(case_path, "physics_report.md")
    if os.path.exists(report_path):
        try:
            with open(report_path, "r") as f:
                return _truncate_report(f.read(), max_chars)
        except Exception as e:
            return f"Error reading physics report: {e}"

    if return_not_found_message:
        return "No physics report found. The PhysicsAnalystAgent has not run yet or did not save the report."
    return ""

def get_physics_report_tool() -> StructuredTool:
    """
    Tool for other agents (like Case Setup) to read the generated physics report.
    """
    return StructuredTool.from_function(
        func=lambda case_path, max_chars=6000: read_physics_report_file(
            case_path,
            return_not_found_message=True,
            max_chars=max_chars,
        ),
        name="get_physics_report",
        description="Get the existing physics analysis report generated by the Physics Analyst. Requires the absolute case_path."
    )
