import os
from langchain.tools import StructuredTool

def read_physics_report_file(case_path: str, return_not_found_message: bool = False) -> str:
    """
    Reads the physics analysis report saved by PhysicsAnalystAgent from the case directory.

    Args:
        case_path: Absolute path to the OpenFOAM case directory.
        return_not_found_message: If True, return a human-readable message when the report is missing;
            otherwise return an empty string on missing report.

    Returns:
        Report content, an empty string if missing (default), or an error message when file read fails.
    """
    if not case_path:
        return "No case_path provided for reading physics_report.md." if return_not_found_message else ""

    report_path = os.path.join(case_path, "physics_report.md")
    if os.path.exists(report_path):
        try:
            with open(report_path, "r") as f:
                return f.read()
        except Exception as e:
            return f"Error reading physics report: {e}"

    if return_not_found_message:
        return "No physics report found. The PhysicsAnalystAgent has not run yet or did not save the report."
    return ""

def get_physics_report_tool() -> StructuredTool:
    """
    Tool for other agents (like Case Setup) to read the generated physics report.
    """
    return StructuredTool.from_function(
        func=lambda case_path: read_physics_report_file(case_path, return_not_found_message=True),
        name="get_physics_report",
        description="Get the existing physics analysis report generated by the Physics Analyst. Requires the absolute case_path."
    )

