import os
from langchain.tools import StructuredTool

def read_review_report_file(case_path: str, return_not_found_message: bool = False) -> str:
    """
    Reads the review report saved by ReviewerAgent from the case directory.

    Args:
        case_path: Absolute path to the OpenFOAM case directory.
        return_not_found_message: If True, return a human-readable message when the report is missing;
            otherwise return an empty string on missing report.

    Returns:
        Report content, an empty string if missing (default), or an error message when file read fails.
    """
    if not case_path:
        return "No case_path provided for reading review_report.md." if return_not_found_message else ""

    report_path = os.path.join(case_path, "review_report.md")
    if os.path.exists(report_path):
        try:
            with open(report_path, "r") as f:
                return f.read()
        except Exception as e:
            return f"Error reading review report: {e}"

    if return_not_found_message:
        return "No review report found. The ReviewerAgent has not run yet or did not save the report."
    return ""

def get_review_report_tool() -> StructuredTool:
    """
    Tool for other agents (like Orchestrator) to read the generated review report.
    """
    return StructuredTool.from_function(
        func=lambda case_path: read_review_report_file(case_path, return_not_found_message=True),
        name="get_review_report",
        description="Get the existing review report generated by the Reviewer Agent. Requires the absolute case_path."
    )
